### PR TITLE
Add model B+ information to MODEL_DATA dictionary

### PR DESCRIPTION
**Pull request by CorCornelisse**
Adds Model B+ to MODEL_DATA dictionary per http://elinux.org/RPi_HardwareHistory 

This addresses an outstanding issue, preventing RPIO to work on Model B+ RaspberryPis.

### CODE REVIEW

**Comment by samadhi82** [comment]
Many thanks for the fix.

**Comment by braveheartwilliam** [comment]
After applying all of the changes inpull #35 manually and rerunning setup.py, the RPIO and RPIO-CURSES worked 100%. I then hooked up some motors to my RPi B+ and wrote a quick Python program to test and all worked. Then, I tried the TCP/IP interrupts and that code worked as well. In a Python program, I could control the motors using http://{RPi IP ADDRESS}:{specified socket}/{custom command} and then use command to cause motors to run. (Used L293D to control motors direction and speed using the RPIO PWM code on the L293D "Enable" pin of each motor.). Got caught initially using channels that are used by other services but then read posts that listed channels to avoid.

**Comment by metachris** [comment]
Thanks, will review on the weekend!

**Comment by metachris** [comment]
Could you update the PR with the latest source? I've merged a few PRs in the meantime!

**Comment by CorCornelisse** [comment]
PR is now up-to-date with upstream. Doesn't include Pi 2 support yet.  Haven't tested camera led gpio on B+ either, since I've got no camera module.

**Comment by metachris** [comment]
Thanks :+1:

**Pull request merged**
